#!/usr/bin/env python3
"""
Portfolio Correlation Analysis — Mom15 + RS63 + ETF Core
=========================================================
Reads three month-end NAV CSV files (generated by each strategy's backtest)
and computes pairwise correlations, individual stats, and equal-weight portfolio stats.

Prerequisites (run each backtest once to generate CSVs):
    python3 rs63_pit_report.py       → rs63_monthly.csv
    python3 mom15_pit_report.py      → mom15_rebal.csv
    python3 data/etf_core_backtest.py → etf_monthly.csv

Usage:
    python3 portfolio_correlation.py
"""

import os
import sys
import numpy as np
import pandas as pd

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

COMMON_START = "2019-01-01"
COMMON_END   = "2026-04-30"

# ── Load CSVs ────────────────────────────────────────────────────────────────
def load_nav(filename, label):
    path = os.path.join(BASE_DIR, filename)
    if not os.path.exists(path):
        print(f"  ERROR: {filename} not found. Run the {label} backtest first.")
        return None
    df = pd.read_csv(path, parse_dates=["date"]).set_index("date")["nav"]
    print(f"  {label:10s}: {len(df)} rows  {df.index[0].date()} → {df.index[-1].date()}  "
          f"Final NAV: ₹{df.iloc[-1]:,.0f}")
    return df

print("=" * 65)
print("  PORTFOLIO CORRELATION ANALYSIS")
print("  Common window:", COMMON_START, "→", COMMON_END)
print("=" * 65)
print()
print("Loading NAV series:")

rs63  = load_nav("rs63_monthly.csv",  "RS63")
mom15 = load_nav("mom15_rebal.csv",   "Mom15")
etf   = load_nav("etf_monthly.csv",   "ETF Core")

if any(x is None for x in [rs63, mom15, etf]):
    sys.exit(1)

# ── Align to Mom15 rebalance dates (bimonthly cadence) ───────────────────────
# Mom15 only has NAV at bimonthly rebalance dates. Aligning RS63 and ETF Core
# to those same dates avoids the ffill zero-return artifact that destroys
# correlation signal. All three series use the same observation dates.
mom15_dates = mom15.index
rs63_m  = rs63.reindex(mom15_dates, method="nearest", tolerance=pd.Timedelta("5d"))
etf_m   = etf.reindex(mom15_dates, method="nearest", tolerance=pd.Timedelta("5d"))
mom15_m = mom15

df_nav = pd.DataFrame({"Mom15": mom15_m, "RS63": rs63_m, "ETF": etf_m})
df_nav = df_nav.loc[COMMON_START:COMMON_END].dropna()

print(f"\n  Common window: {len(df_nav)} bimonthly observations (Mom15 rebalance dates)")
if len(df_nav) < 12:
    print("  WARNING: fewer than 12 observations — results may not be meaningful.")

# ── Bimonthly returns ─────────────────────────────────────────────────────────
rets = df_nav.pct_change().dropna()

# ── Individual strategy stats ─────────────────────────────────────────────────
PERIODS_PER_YEAR = 6  # bimonthly (Mom15 rebalance cadence)

def strategy_stats(r, label):
    ann_ret = (1 + r.mean()) ** PERIODS_PER_YEAR - 1
    ann_vol = r.std() * np.sqrt(PERIODS_PER_YEAR)
    sharpe  = ann_ret / ann_vol if ann_vol > 0 else 0
    nav_cum = (1 + r).cumprod()
    max_dd  = (nav_cum / nav_cum.cummax() - 1).min()
    neg_yrs = sum(1 for yr, g in r.groupby(r.index.year) if g.sum() < 0)
    return {"label": label, "ann_ret": ann_ret, "ann_vol": ann_vol,
            "sharpe": sharpe, "max_dd": max_dd, "neg_yrs": neg_yrs}

stats = [
    strategy_stats(rets["Mom15"], "Mom15"),
    strategy_stats(rets["RS63"],  "RS63"),
    strategy_stats(rets["ETF"],   "ETF Core"),
]

# Equal-weight portfolio
rets["Portfolio"] = rets[["Mom15", "RS63", "ETF"]].mean(axis=1)
stats.append(strategy_stats(rets["Portfolio"], "Portfolio (1/3 each)"))

print()
print("=" * 65)
print("  INDIVIDUAL STRATEGY STATS  (common window only)")
print("=" * 65)
print(f"  {'Strategy':<22} {'AnnRet':>8} {'AnnVol':>8} {'Sharpe':>8} {'MaxDD':>8} {'NegYrs':>7}")
print(f"  {'-'*22} {'-'*8} {'-'*8} {'-'*8} {'-'*8} {'-'*7}")
for s in stats:
    print(f"  {s['label']:<22} {s['ann_ret']:>7.1%} {s['ann_vol']:>7.1%} "
          f"{s['sharpe']:>8.2f} {s['max_dd']:>7.1%} {s['neg_yrs']:>7}")

# ── Correlation matrix ────────────────────────────────────────────────────────
corr = rets[["Mom15", "RS63", "ETF"]].corr().round(3)

print()
print("=" * 65)
print("  PAIRWISE CORRELATION MATRIX  (monthly returns)")
print("=" * 65)
print(corr.to_string())

print()
key_corrs = {
    "Mom15 ↔ RS63":   corr.loc["Mom15", "RS63"],
    "Mom15 ↔ ETF":    corr.loc["Mom15", "ETF"],
    "RS63  ↔ ETF":    corr.loc["RS63",  "ETF"],
}
for pair, val in key_corrs.items():
    assessment = ("HIGH — limited diversification" if val > 0.7
                  else "MODERATE — some diversification" if val > 0.4
                  else "LOW — strong diversification")
    print(f"  {pair}: {val:+.3f}  [{assessment}]")

# ── Rolling 12-month correlations ─────────────────────────────────────────────
roll = pd.DataFrame({
    "Mom15-RS63": rets["Mom15"].rolling(6).corr(rets["RS63"]),   # 6 bimonthly = 1 year
    "Mom15-ETF":  rets["Mom15"].rolling(6).corr(rets["ETF"]),
    "RS63-ETF":   rets["RS63"].rolling(6).corr(rets["ETF"]),
}).dropna()

roll_csv = os.path.join(BASE_DIR, "rolling_corr.csv")
roll.to_csv(roll_csv)

print()
print("=" * 65)
print("  ROLLING 1-YEAR CORRELATION (6 bimonthly obs, min / avg / max)")
print("=" * 65)
for col in roll.columns:
    s = roll[col]
    print(f"  {col:<15}: min={s.min():+.2f}  avg={s.mean():+.2f}  max={s.max():+.2f}")
print(f"\n  Full rolling series saved → rolling_corr.csv")

# ── Year-by-year comparison ───────────────────────────────────────────────────
print()
print("=" * 65)
print("  YEAR-BY-YEAR RETURNS  (% annual, common window)")
print("=" * 65)
print(f"  {'Year':>4}  {'Mom15':>8}  {'RS63':>8}  {'ETF':>8}  {'Portfolio':>10}")
print(f"  {'-'*4}  {'-'*8}  {'-'*8}  {'-'*8}  {'-'*10}")
for yr, g in rets.groupby(rets.index.year):
    yr_ret = (1 + g).prod() - 1
    print(f"  {yr:>4}  {yr_ret['Mom15']:>+7.1%}  {yr_ret['RS63']:>+7.1%}  "
          f"{yr_ret['ETF']:>+7.1%}  {yr_ret['Portfolio']:>+9.1%}")

# ── Weight grid: does Mom15 earn a small slot? ────────────────────────────────
print()
print("=" * 65)
print("  WEIGHT GRID  (RS63 / ETF / Mom15 allocations)")
print("=" * 65)
print(f"  {'Portfolio':<28} {'AnnRet':>8} {'AnnVol':>8} {'Sharpe':>8} {'MaxDD':>8} {'Calmar':>7}")
print(f"  {'-'*28} {'-'*8} {'-'*8} {'-'*8} {'-'*8} {'-'*7}")

configs = [
    ("RS63 alone",              1.00, 0.00, 0.00),
    ("ETF alone",               0.00, 1.00, 0.00),
    ("Mom15 alone",             0.00, 0.00, 1.00),
    ("RS63+ETF  50/50",         0.50, 0.50, 0.00),
    ("Mom15+ETF 50/50",         0.00, 0.50, 0.50),
    ("Mom15+RS63 50/50",        0.50, 0.00, 0.50),
    ("33/33/33",                0.33, 0.34, 0.33),
    ("RS63/ETF/Mom15 40/40/20", 0.40, 0.40, 0.20),
    ("RS63/ETF/Mom15 45/40/15", 0.45, 0.40, 0.15),
    ("RS63/ETF/Mom15 50/40/10", 0.50, 0.40, 0.10),
]

for label, w_rs63, w_etf, w_mom15 in configs:
    r = rets["RS63"] * w_rs63 + rets["ETF"] * w_etf + rets["Mom15"] * w_mom15
    ann_ret = (1 + r.mean()) ** PERIODS_PER_YEAR - 1
    ann_vol = r.std() * np.sqrt(PERIODS_PER_YEAR)
    sharpe  = ann_ret / ann_vol if ann_vol > 0 else 0
    nav_cum = (1 + r).cumprod()
    max_dd  = (nav_cum / nav_cum.cummax() - 1).min()
    calmar  = ann_ret / abs(max_dd) if max_dd != 0 else 0
    marker  = " ◄" if label == "RS63+ETF  50/50" else ""
    print(f"  {label:<28} {ann_ret:>7.1%} {ann_vol:>7.1%} {sharpe:>8.2f} {max_dd:>7.1%} {calmar:>7.2f}{marker}")

print()
print("=" * 65)
