# Stock to Sector Index Mapping
# Maps stock tickers to their primary sector index
# Complete mapping for all Nifty 500 stocks

STOCK_SECTOR_MAP = {
    # ============ BANKING - Private ============
    "HDFCBANK": "NIFTY PVT BANK", "ICICIBANK": "NIFTY PVT BANK", "KOTAKBANK": "NIFTY PVT BANK",
    "AXISBANK": "NIFTY PVT BANK", "INDUSINDBK": "NIFTY PVT BANK", "BANDHANBNK": "NIFTY PVT BANK",
    "FEDERALBNK": "NIFTY PVT BANK", "IDFCFIRSTB": "NIFTY PVT BANK", "RBLBANK": "NIFTY PVT BANK",
    "AUBANK": "NIFTY PVT BANK", "CUB": "NIFTY PVT BANK", "KARURVYSYA": "NIFTY PVT BANK",
    "YESBANK": "NIFTY PVT BANK",

    # ============ BANKING - PSU ============
    "SBIN": "NIFTY PSU BANK", "BANKBARODA": "NIFTY PSU BANK", "PNB": "NIFTY PSU BANK",
    "CANBK": "NIFTY PSU BANK", "UNIONBANK": "NIFTY PSU BANK", "IOB": "NIFTY PSU BANK",
    "INDIANB": "NIFTY PSU BANK", "BANKINDIA": "NIFTY PSU BANK", "CENTRALBK": "NIFTY PSU BANK",
    "MAHABANK": "NIFTY PSU BANK", "IDBI": "NIFTY PSU BANK", "J&KBANK": "NIFTY PSU BANK",
    "UCOBANK": "NIFTY PSU BANK",

    # ============ IT ============
    "TCS": "NIFTY IT", "INFY": "NIFTY IT", "HCLTECH": "NIFTY IT", "WIPRO": "NIFTY IT",
    "TECHM": "NIFTY IT", "LTIM": "NIFTY IT", "LTTS": "NIFTY IT", "MPHASIS": "NIFTY IT",
    "COFORGE": "NIFTY IT", "PERSISTENT": "NIFTY IT", "KPITTECH": "NIFTY IT", "CYIENT": "NIFTY IT",
    "ECLERX": "NIFTY IT", "TATAELXSI": "NIFTY IT", "BSOFT": "NIFTY IT", "HAPPSTMNDS": "NIFTY IT",
    "INTELLECT": "NIFTY IT", "LATENTVIEW": "NIFTY IT", "NEWGEN": "NIFTY IT",
    "OFSS": "NIFTY IT", "SONATSOFTW": "NIFTY IT", "ZENSARTECH": "NIFTY IT",
    "DATAPATTNS": "NIFTY IT", "NETWEB": "NIFTY IT", "TATATECH": "NIFTY IT",
    "MAPMYINDIA": "NIFTY IT", "AFFLE": "NIFTY IT", "INDIAMART": "NIFTY IT",
    "NAUKRI": "NIFTY IT", "SYRMA": "NIFTY IT", "KAYNES": "NIFTY IT",
    "Dixon": "NIFTY IT", "ZENTEC": "NIFTY IT", "IKS": "NIFTY IT",

    # ============ PHARMA ============
    "SUNPHARMA": "NIFTY PHARMA", "DRREDDY": "NIFTY PHARMA", "CIPLA": "NIFTY PHARMA",
    "DIVISLAB": "NIFTY PHARMA", "LUPIN": "NIFTY PHARMA", "AUROPHARMA": "NIFTY PHARMA",
    "BIOCON": "NIFTY PHARMA", "TORNTPHARM": "NIFTY PHARMA", "ALKEM": "NIFTY PHARMA",
    "GLENMARK": "NIFTY PHARMA", "IPCALAB": "NIFTY PHARMA", "LAURUSLABS": "NIFTY PHARMA",
    "ABBOTINDIA": "NIFTY PHARMA", "GLAXO": "NIFTY PHARMA", "PFIZER": "NIFTY PHARMA",
    "MANKIND": "NIFTY PHARMA", "AJANTPHARM": "NIFTY PHARMA", "GRANULES": "NIFTY PHARMA",
    "NATCOPHARM": "NIFTY PHARMA", "EMCURE": "NIFTY PHARMA", "JBCHEPHARM": "NIFTY PHARMA",
    "ZYDUSLIFE": "NIFTY PHARMA", "SYNGENE": "NIFTY PHARMA", "GLAND": "NIFTY PHARMA",
    "ERIS": "NIFTY PHARMA", "WOCKPHARMA": "NIFTY PHARMA", "NEULANDLAB": "NIFTY PHARMA",
    "PPLPHARMA": "NIFTY PHARMA", "JUBLPHARMA": "NIFTY PHARMA", "AKUMS": "NIFTY PHARMA",
    "ASTRAZEN": "NIFTY PHARMA", "CONCORDBIO": "NIFTY PHARMA", "COHANCE": "NIFTY PHARMA",
    "CAPLIPOINT": "NIFTY PHARMA",

    # ============ AUTO ============
    "MARUTI": "NIFTY AUTO", "TATAMOTORS": "NIFTY AUTO", "M&M": "NIFTY AUTO",
    "BAJAJ-AUTO": "NIFTY AUTO", "HEROMOTOCO": "NIFTY AUTO", "EICHERMOT": "NIFTY AUTO",
    "ASHOKLEY": "NIFTY AUTO", "TVSMOTOR": "NIFTY AUTO", "BALKRISIND": "NIFTY AUTO",
    "APOLLOTYRE": "NIFTY AUTO", "MRF": "NIFTY AUTO", "BHARATFORG": "NIFTY AUTO",
    "BOSCHLTD": "NIFTY AUTO", "MOTHERSON": "NIFTY AUTO", "EXIDEIND": "NIFTY AUTO",
    "CEATLTD": "NIFTY AUTO", "JKTYRE": "NIFTY AUTO", "ESCORTS": "NIFTY AUTO",
    "FORCEMOT": "NIFTY AUTO", "HYUNDAI": "NIFTY AUTO", "ENDURANCE": "NIFTY AUTO",
    "SONACOMS": "NIFTY AUTO", "UNOMINDA": "NIFTY AUTO", "CRAFTSMAN": "NIFTY AUTO",
    "SUNDRMFAST": "NIFTY AUTO", "MAHSEAMLES": "NIFTY AUTO", "TITAGARH": "NIFTY AUTO",
    "OLECTRA": "NIFTY AUTO", "OLAELEC": "NIFTY AUTO", "JBMA": "NIFTY AUTO",

    # ============ METAL ============
    "TATASTEEL": "NIFTY METAL", "HINDALCO": "NIFTY METAL", "JSWSTEEL": "NIFTY METAL",
    "VEDL": "NIFTY METAL", "COALINDIA": "NIFTY METAL", "NMDC": "NIFTY METAL",
    "HINDCOPPER": "NIFTY METAL", "NATIONALUM": "NIFTY METAL", "SAIL": "NIFTY METAL",
    "JINDALSTEL": "NIFTY METAL", "HINDZINC": "NIFTY METAL", "APLAPOLLO": "NIFTY METAL",
    "JINDALSAW": "NIFTY METAL", "WELCORP": "NIFTY METAL", "JSL": "NIFTY METAL",
    "GPIL": "NIFTY METAL", "SHYAMMETL": "NIFTY METAL", "GRAVITA": "NIFTY METAL",
    "RKFORGE": "NIFTY METAL", "NSLNISP": "NIFTY METAL",

    # ============ ENERGY / OIL & GAS ============
    "RELIANCE": "NIFTY ENERGY", "ONGC": "NIFTY ENERGY", "NTPC": "NIFTY ENERGY",
    "POWERGRID": "NIFTY ENERGY", "BPCL": "NIFTY ENERGY", "IOC": "NIFTY ENERGY",
    "GAIL": "NIFTY ENERGY", "HINDPETRO": "NIFTY ENERGY", "PETRONET": "NIFTY ENERGY",
    "ADANIGREEN": "NIFTY ENERGY", "TATAPOWER": "NIFTY ENERGY", "ADANIENSOL": "NIFTY ENERGY",
    "ADANIPOWER": "NIFTY ENERGY", "JSWENERGY": "NIFTY ENERGY", "TORNTPOWER": "NIFTY ENERGY",
    "NHPC": "NIFTY ENERGY", "SJVN": "NIFTY ENERGY", "IGL": "NIFTY ENERGY",
    "MGL": "NIFTY ENERGY", "GUJGASLTD": "NIFTY ENERGY", "GSPL": "NIFTY ENERGY",
    "CHENNPETRO": "NIFTY ENERGY", "MRPL": "NIFTY ENERGY", "OIL": "NIFTY ENERGY",
    "CESC": "NIFTY ENERGY", "NTPCGREEN": "NIFTY ENERGY", "JPPOWER": "NIFTY ENERGY",
    "RPOWER": "NIFTY ENERGY", "ATGL": "NIFTY ENERGY", "IREDA": "NIFTY ENERGY",
    "NLCINDIA": "NIFTY ENERGY", "WAAREEENER": "NIFTY ENERGY", "ACMESOLAR": "NIFTY ENERGY",
    "PREMIERENE": "NIFTY ENERGY", "SUZLON": "NIFTY ENERGY", "INOXWIND": "NIFTY ENERGY",

    # ============ FMCG ============
    "HINDUNILVR": "NIFTY FMCG", "ITC": "NIFTY FMCG", "NESTLEIND": "NIFTY FMCG",
    "BRITANNIA": "NIFTY FMCG", "DABUR": "NIFTY FMCG", "MARICO": "NIFTY FMCG",
    "COLPAL": "NIFTY FMCG", "GODREJCP": "NIFTY FMCG", "TATACONSUM": "NIFTY FMCG",
    "VBL": "NIFTY FMCG", "UBL": "NIFTY FMCG", "MCDOWELL-N": "NIFTY FMCG",
    "PGHH": "NIFTY FMCG", "EMAMILTD": "NIFTY FMCG", "RADICO": "NIFTY FMCG",
    "BATAINDIA": "NIFTY FMCG", "JYOTHYLAB": "NIFTY FMCG", "BIKAJI": "NIFTY FMCG",
    "GODFRYPHLP": "NIFTY FMCG", "HONASA": "NIFTY FMCG", "PATANJALI": "NIFTY FMCG",
    "LTFOODS": "NIFTY FMCG", "BALRAMCHIN": "NIFTY FMCG", "EIDPARRY": "NIFTY FMCG",
    "BBTC": "NIFTY FMCG", "CCL": "NIFTY FMCG", "GILLETTE": "NIFTY FMCG",

    # ============ REALTY ============
    "DLF": "NIFTY REALTY", "GODREJPROP": "NIFTY REALTY", "OBEROIRLTY": "NIFTY REALTY",
    "PHOENIXLTD": "NIFTY REALTY", "PRESTIGE": "NIFTY REALTY", "BRIGADE": "NIFTY REALTY",
    "LODHA": "NIFTY REALTY", "SOBHA": "NIFTY REALTY", "ANANTRAJ": "NIFTY REALTY",
    "DBREALTY": "NIFTY REALTY", "SIGNATURE": "NIFTY REALTY", "MAHLIFE": "NIFTY REALTY",

    # ============ FINANCIAL SERVICES (Non-Bank) ============
    "BAJFINANCE": "NIFTY FIN SERVICE", "BAJAJFINSV": "NIFTY FIN SERVICE", "HDFCAMC": "NIFTY FIN SERVICE",
    "SBILIFE": "NIFTY FIN SERVICE", "HDFCLIFE": "NIFTY FIN SERVICE", "ICICIPRULI": "NIFTY FIN SERVICE",
    "ICICIGI": "NIFTY FIN SERVICE", "MUTHOOTFIN": "NIFTY FIN SERVICE", "CHOLAFIN": "NIFTY FIN SERVICE",
    "SHRIRAMFIN": "NIFTY FIN SERVICE", "M&MFIN": "NIFTY FIN SERVICE", "LICHSGFIN": "NIFTY FIN SERVICE",
    "MANAPPURAM": "NIFTY FIN SERVICE", "CANFINHOME": "NIFTY FIN SERVICE", "POONAWALLA": "NIFTY FIN SERVICE",
    "ABCAPITAL": "NIFTY FIN SERVICE", "LICI": "NIFTY FIN SERVICE", "GICRE": "NIFTY FIN SERVICE",
    "NIACL": "NIFTY FIN SERVICE", "SBICARD": "NIFTY FIN SERVICE", "PFC": "NIFTY FIN SERVICE",
    "RECLTD": "NIFTY FIN SERVICE", "IRFC": "NIFTY FIN SERVICE", "HUDCO": "NIFTY FIN SERVICE",
    "360ONE": "NIFTY FIN SERVICE", "ANANDRATHI": "NIFTY FIN SERVICE", "ANGELONE": "NIFTY FIN SERVICE",
    "AADHARHFC": "NIFTY FIN SERVICE", "AAVAS": "NIFTY FIN SERVICE", "BAJAJHFL": "NIFTY FIN SERVICE",
    "HOMEFIRST": "NIFTY FIN SERVICE", "PNBHOUSING": "NIFTY FIN SERVICE", "APTUS": "NIFTY FIN SERVICE",
    "CAMS": "NIFTY FIN SERVICE", "CDSL": "NIFTY FIN SERVICE", "BSE": "NIFTY FIN SERVICE",
    "MCX": "NIFTY FIN SERVICE", "IEX": "NIFTY FIN SERVICE", "KFINTECH": "NIFTY FIN SERVICE",
    "FIVESTAR": "NIFTY FIN SERVICE", "CREDITACC": "NIFTY FIN SERVICE", "SUNDARMFIN": "NIFTY FIN SERVICE",
    "CHOLAHLDNG": "NIFTY FIN SERVICE", "BAJAJHLDNG": "NIFTY FIN SERVICE", "MOTILALOFS": "NIFTY FIN SERVICE",
    "MFSL": "NIFTY FIN SERVICE", "ABSLAMC": "NIFTY FIN SERVICE", "UTIAMC": "NIFTY FIN SERVICE",
    "NAM-INDIA": "NIFTY FIN SERVICE", "NUVAMA": "NIFTY FIN SERVICE", "JIOFIN": "NIFTY FIN SERVICE",
    "JMFINANCIL": "NIFTY FIN SERVICE", "STARHEALTH": "NIFTY FIN SERVICE", "NIVABUPA": "NIFTY FIN SERVICE",
    "GODIGIT": "NIFTY FIN SERVICE", "PAYTM": "NIFTY FIN SERVICE", "POLICYBZR": "NIFTY FIN SERVICE",
    "SBFC": "NIFTY FIN SERVICE", "SAMMAANCAP": "NIFTY FIN SERVICE", "LTF": "NIFTY FIN SERVICE",
    "IIFL": "NIFTY FIN SERVICE", "CHOICEIN": "NIFTY FIN SERVICE",

    # ============ INFRA / CAPITAL GOODS ============
    "LT": "NIFTY INFRA", "ADANIPORTS": "NIFTY INFRA", "ULTRACEMCO": "NIFTY INFRA",
    "GRASIM": "NIFTY INFRA", "ACC": "NIFTY INFRA", "AMBUJACEM": "NIFTY INFRA",
    "SHREECEM": "NIFTY INFRA", "DALBHARAT": "NIFTY INFRA", "RAMCOCEM": "NIFTY INFRA",
    "JKCEMENT": "NIFTY INFRA", "INDIACEM": "NIFTY INFRA", "JSWINFRA": "NIFTY INFRA",
    "IRB": "NIFTY INFRA", "KEC": "NIFTY INFRA", "GMRAIRPORT": "NIFTY INFRA",
    "CONCOR": "NIFTY INFRA", "IRCON": "NIFTY INFRA", "NBCC": "NIFTY INFRA",
    "ADANIENT": "NIFTY INFRA", "SIEMENS": "NIFTY INFRA", "ABB": "NIFTY INFRA",
    "HAVELLS": "NIFTY INFRA", "CGPOWER": "NIFTY INFRA", "CUMMINSIND": "NIFTY INFRA",
    "THERMAX": "NIFTY INFRA", "VOLTAS": "NIFTY INFRA", "CROMPTON": "NIFTY INFRA",
    "BLUESTARCO": "NIFTY INFRA", "POLYCAB": "NIFTY INFRA", "KEI": "NIFTY INFRA",
    "RRKABEL": "NIFTY INFRA", "FINCABLES": "NIFTY INFRA", "HFCL": "NIFTY INFRA",
    "NCC": "NIFTY INFRA", "RVNL": "NIFTY INFRA", "ENGINERSIN": "NIFTY INFRA",
    "RITES": "NIFTY INFRA", "BHEL": "NIFTY INFRA", "BEL": "NIFTY INFRA",
    "HAL": "NIFTY INFRA", "BDL": "NIFTY INFRA", "BEML": "NIFTY INFRA",
    "GRSE": "NIFTY INFRA", "MAZDOCK": "NIFTY INFRA", "COCHINSHIP": "NIFTY INFRA",
    "JSWCEMENT": "NIFTY INFRA", "NUVOCO": "NIFTY INFRA", "KPIL": "NIFTY INFRA",
    "AFCONS": "NIFTY INFRA", "HSCL": "NIFTY INFRA", "ELECON": "NIFTY INFRA",
    "ELGIEQUIP": "NIFTY INFRA", "TRITURBINE": "NIFTY INFRA", "HONAUT": "NIFTY INFRA",
    "TIINDIA": "NIFTY INFRA", "TIMKEN": "NIFTY INFRA", "SCHAEFFLER": "NIFTY INFRA",
    "KIRLOSBROS": "NIFTY INFRA", "KIRLOSENG": "NIFTY INFRA", "KSB": "NIFTY INFRA",
    "RAILTEL": "NIFTY INFRA", "INOXINDIA": "NIFTY INFRA", "ITI": "NIFTY INFRA",
    "TEJASNET": "NIFTY INFRA", "LLOYDSME": "NIFTY INFRA", "GVT&D": "NIFTY INFRA",
    "POWERINDIA": "NIFTY INFRA", "SCHNEIDER": "NIFTY INFRA", "CENTURYPLY": "NIFTY INFRA",
    "ASTRAL": "NIFTY INFRA", "SUPREMEIND": "NIFTY INFRA", "FINPIPE": "NIFTY INFRA",
    "PIDILITIND": "NIFTY INFRA", "BERGEPAINT": "NIFTY INFRA", "ASIANPAINT": "NIFTY INFRA",
    "INDIGO": "NIFTY INFRA", "IRCTC": "NIFTY INFRA", "AEGISLOG": "NIFTY INFRA",
    "DELHIVERY": "NIFTY INFRA", "BLUEDART": "NIFTY INFRA", "TBOTEK": "NIFTY INFRA",
    "TRIVENI": "NIFTY INFRA", "PRAJIND": "NIFTY INFRA", "ACE": "NIFTY INFRA",
    "HBLENGINE": "NIFTY INFRA",

    # ============ HEALTHCARE ============
    "APOLLOHOSP": "NIFTY HEALTHCARE", "FORTIS": "NIFTY HEALTHCARE", "MAXHEALTH": "NIFTY HEALTHCARE",
    "LALPATHLAB": "NIFTY HEALTHCARE", "METROPOLIS": "NIFTY HEALTHCARE", "KIMS": "NIFTY HEALTHCARE",
    "MEDANTA": "NIFTY HEALTHCARE", "RAINBOW": "NIFTY HEALTHCARE", "NH": "NIFTY HEALTHCARE",
    "AGARWALEYE": "NIFTY HEALTHCARE", "ASTERDM": "NIFTY HEALTHCARE",

    # ============ MEDIA ============
    "ZEEL": "NIFTY MEDIA", "SUNTV": "NIFTY MEDIA", "PVRINOX": "NIFTY MEDIA",
    "NETWORK18": "NIFTY MEDIA", "SAREGAMA": "NIFTY MEDIA",

    # ============ PSE ============
    "IRCTC": "NIFTY PSE", "BHEL": "NIFTY PSE", "BEL": "NIFTY PSE",
    "HAL": "NIFTY PSE", "MMTC": "NIFTY PSE", "GMDCLTD": "NIFTY PSE",
    "SCI": "NIFTY PSE", "FACT": "NIFTY PSE", "RCF": "NIFTY PSE",
    "IFCI": "NIFTY PSE",

    # ============ CONSUMPTION ============
    "TITAN": "NIFTY CONSUMPTION", "TRENT": "NIFTY CONSUMPTION", "PAGEIND": "NIFTY CONSUMPTION",
    "JUBLFOOD": "NIFTY CONSUMPTION", "DEVYANI": "NIFTY CONSUMPTION", "DMART": "NIFTY CONSUMPTION",
    "RELAXO": "NIFTY CONSUMPTION", "KALYANKJIL": "NIFTY CONSUMPTION",
    "NYKAA": "NIFTY CONSUMPTION", "MANYAVAR": "NIFTY CONSUMPTION", "CAMPUS": "NIFTY CONSUMPTION",
    "INDHOTEL": "NIFTY CONSUMPTION", "LEMONTRE": "NIFTY CONSUMPTION", "CHALET": "NIFTY CONSUMPTION",
    "EIHOTEL": "NIFTY CONSUMPTION", "THELEELA": "NIFTY CONSUMPTION", "ETERNAL": "NIFTY CONSUMPTION",
    "FIRSTCRY": "NIFTY CONSUMPTION", "SWIGGY": "NIFTY CONSUMPTION",

    # ============ COMMODITIES / CHEMICALS ============
    "AARTIIND": "NIFTY COMMODITIES", "ALKYLAMINE": "NIFTY COMMODITIES", "ATUL": "NIFTY COMMODITIES",
    "DEEPAKNTR": "NIFTY COMMODITIES", "NAVINFLUOR": "NIFTY COMMODITIES", "PIIND": "NIFTY COMMODITIES",
    "SRF": "NIFTY COMMODITIES", "FLUOROCHEM": "NIFTY COMMODITIES", "CLEAN": "NIFTY COMMODITIES",
    "TATACHEM": "NIFTY COMMODITIES", "DCMSHRIRAM": "NIFTY COMMODITIES", "CHAMBLFERT": "NIFTY COMMODITIES",
    "COROMANDEL": "NIFTY COMMODITIES", "DEEPAKFERT": "NIFTY COMMODITIES", "SUMICHEM": "NIFTY COMMODITIES",
    "UPL": "NIFTY COMMODITIES", "BASF": "NIFTY COMMODITIES", "CASTROLIND": "NIFTY COMMODITIES",
    "PCBL": "NIFTY COMMODITIES", "HEG": "NIFTY COMMODITIES", "GRAPHITE": "NIFTY COMMODITIES",
    "CARBORUNIV": "NIFTY COMMODITIES", "BLUEJET": "NIFTY COMMODITIES", "NAVA": "NIFTY COMMODITIES",
    "APLLTD": "NIFTY COMMODITIES", "AIAENG": "NIFTY COMMODITIES",

    # ============ MNC ============
    "3MINDIA": "NIFTY MNC", "AKZOINDIA": "NIFTY MNC", "ASAHIINDIA": "NIFTY MNC",
    "BAYERCROP": "NIFTY MNC", "CRISIL": "NIFTY MNC", "WHIRLPOOL": "NIFTY MNC",
    "LINDEINDIA": "NIFTY MNC",

    # ============ TELECOM ============
    "BHARTIARTL": "NIFTY INFRA", "IDEA": "NIFTY INFRA", "TATACOMM": "NIFTY INFRA",
    "INDUSTOWER": "NIFTY INFRA", "BHARTIHEXA": "NIFTY INFRA", "TTML": "NIFTY INFRA",

    # ============ TEXTILE ============
    "TRIDENT": "NIFTY COMMODITIES", "WELSPUNLIV": "NIFTY COMMODITIES", "KPRMILL": "NIFTY COMMODITIES",
    "VGUARD": "NIFTY CONSUMPTION",

    # ============ DIVERSIFIED / OTHERS ============
    "ABFRL": "NIFTY CONSUMPTION", "APARINDS": "NIFTY COMMODITIES", "ARE&M": "NIFTY INFRA",
    "AWL": "NIFTY FMCG", "AMBER": "NIFTY CONSUMPTION", "BLS": "NIFTY FIN SERVICE",
    "CERA": "NIFTY CONSUMPTION", "CGCL": "NIFTY FIN SERVICE", "DIXON": "NIFTY CONSUMPTION",
    "FSL": "NIFTY PHARMA", "GESHIP": "NIFTY INFRA", "GODREJAGRO": "NIFTY COMMODITIES",
    "GODREJIND": "NIFTY COMMODITIES", "HEXT": "NIFTY COMMODITIES", "IGIL": "NIFTY COMMODITIES",
    "INDGN": "NIFTY ENERGY", "JYOTICNC": "NIFTY INFRA", "JWL": "NIFTY CONSUMPTION",
    "KAJARIACER": "NIFTY CONSUMPTION", "LEMONTREE": "NIFTY CONSUMPTION", "MAHSCOOTER": "NIFTY AUTO",
    "MINDACORP": "NIFTY AUTO", "MSUMI": "NIFTY AUTO", "POLYMED": "NIFTY HEALTHCARE",
    "PTCIL": "NIFTY ENERGY", "REDINGTON": "NIFTY IT", "RHIM": "NIFTY INFRA",
    "SAGILITY": "NIFTY IT", "SAILIFE": "NIFTY PHARMA", "SAPPHIRE": "NIFTY CONSUMPTION",
    "SARDAEN": "NIFTY ENERGY", "SOLARINDS": "NIFTY COMMODITIES", "SWANCORP": "NIFTY CONSUMPTION",
    "TARIL": "NIFTY COMMODITIES", "TATAINVEST": "NIFTY FIN SERVICE", "TECHNOE": "NIFTY INFRA",
    "TMPV": "NIFTY MEDIA", "UNITDSPR": "NIFTY FMCG", "USHAMART": "NIFTY CONSUMPTION",
    "VENTIVE": "NIFTY INFRA", "VIJAYA": "NIFTY FMCG", "VMM": "NIFTY INFRA",
    "VTL": "NIFTY INFRA", "ZFCVINDIA": "NIFTY AUTO", "ONESOURCE": "NIFTY FIN SERVICE",
    "AEGISVOPAK": "NIFTY ENERGY", "AIIL": "NIFTY COMMODITIES", "ALOKINDS": "NIFTY COMMODITIES",
    "ABLBL": "NIFTY FMCG", "ABREL": "NIFTY INFRA", "PGEL": "NIFTY ENERGY",
    "ENRIN": "NIFTY INFRA", "JUBLINGREA": "NIFTY COMMODITIES", "ITCHOTELS": "NIFTY CONSUMPTION",
}
